#ifndef PPC_VDEF_H
#define PPC_VDEF_H

#define TWI_OPCD     3
#define MULLI_OPCD   7
#define SUBFIC_OPCD  8
#define CMPLI_OPCD   10
#define CMPL_OPCD    11
#define ADDIC_OPCD   12
#define ADDIC__OPCD  13
#define ADDI_OPCD    14
#define ADDIS_OPCD   15
#define BC_OPCD      16
#define SC_OPCD      17
#define B_OPCD       18
#define MCRF_OPCD    19
#define BCLR_OPCD    19
#define CRNOR_OPCD   19
#define RFI_OPCD     19
#define CRXOR_OPCD   19
#define CRAND_OPCD   19
#define BCCTR_OPCD   19
#define RLWIMI_OPCD  20
#define RLWINM_OPCD  21
#define RLWNM_OPCD   23
#define ORI_OPCD     24
#define ORIS_OPCD    25
#define XORI_OPCD    26
#define XORIS_OPCD   27
#define ANDI__OPCD   28
#define ANDIS__OPCD  29
#define CMP_OPCD     31
#define SUBFC_OPCD   31
#define ADDC_OPCD    31
#define MULHWU_OPCD  31
#define MFCR_OPCD    31
#define LWARX_OPCD   31
#define LWZX_OPCD    31
#define SLW_OPCD     31
#define CNTLZW_OPCD  31
#define AND_OPCD     31
#define CMPL_OPCD    31
#define SUBF_OPCD    31
#define ANDC_OPCD    31
#define MULHW_OPCD   31
#define MFMSR_OPCD   31
#define LBZX_OPCD    31
#define NEG_OPCD     31
#define NOR_OPCD     31
#define SUBFE_OPCD   31
#define ADDE_OPCD    31
#define MTCRF_OPCD   31
#define MTMSR_OPCD   31
#define STWCX__OPCD  31
#define STWX_OPCD    31
#define WRTEEI_OPCD  31
#define SUBFZE_OPCD  31
#define ADDZE_OPCD   31
#define STBX_OPCD    31
#define ADDME_OPCD   31
#define MULLW_OPCD   31
#define ADD_OPCD     31
#define LHZX_OPCD    31
#define XOR_OPCD     31
#define MFSPR_OPCD   31
#define LHAX_OPCD    31
#define STHX_OPCD    31
#define ORC_OPCD     31
#define OR_OPCD      31
#define DIVWU_OPCD   31
#define MTSPR_OPCD   31
#define NAND_OPCD    31
#define DIVW_OPCD    31
#define LWBRX_OPCD   31
#define SRW_OPCD     31
#define SYNC_OPCD    31
#define STWBRX_OPCD  31
#define LHBRX_OPCD   31
#define SRAW_OPCD    31
#define SRAWI_OPCD   31
#define STHBRX_OPCD  31
#define EXTSH_OPCD   31
#define EXTSB_OPCD   31
#define LWZ_OPCD     32
#define LBZ_OPCD     34
#define STW_OPCD     36
#define STB_OPCD     38
#define LHZ_OPCD     40
#define LHA_OPCD     42
#define STH_OPCD     44
#define LMW_OPCD     46
#define STMW_OPCD    47
#define LBZU_OPCD	 35
#define LBZUX_OPCD	 31
#define LHZU_OPCD	 41
#define LHZUX_OPCD	 31
#define LHAU_OPCD	 43
#define LHAUX_OPCD	 31
#define LWZU_OPCD	 33
#define LWZUX_OPCD	 31
#define STBU_OPCD	 39
#define STBUX_OPCD	 31
#define STHU_OPCD	 45
#define STHUX_OPCD	 31
#define STWU_OPCD	 37
#define STWUX_OPCD	 31


#define TWI_XO       0
#define MULLI_XO     0
#define SUBFIC_XO    0
#define CMPLI_XO     0
#define CMPL_XO      0
#define ADDIC_XO     0
#define ADDIC__XO    0
#define ADDI_XO      0
#define ADDIS_XO     0
#define BC_XO        0
#define SC_XO        0
#define B_XO         0
#define MCRF_XO      0
#define BCLR_XO      16
#define CRNOR_XO     33
#define RFI_XO       50
#define CRXOR_XO     193
#define CRAND_XO     257
#define BCCTR_XO     528
#define RLWIMI_XO    0
#define RLWINM_XO    0
#define RLWNM_XO     0
#define ORI_XO       0
#define ORIS_XO      0
#define XORI_XO      0
#define XORIS_XO     0
#define ANDI__XO     0
#define ANDIS__XO    0
#define CMP_XO       0
#define SUBFC_XO     8
#define ADDC_XO      10
#define MULHWU_XO    11
#define MFCR_XO      19
#define LWARX_XO     20
#define LWZX_XO      23
#define SLW_XO       24
#define CNTLZW_XO    26
#define AND_XO       28
#define CMPL_XO      32
#define SUBF_XO      40
#define ANDC_XO      60
#define MULHW_XO     75
#define MFMSR_XO     83
#define LBZX_XO      87
#define NEG_XO       104
#define NOR_XO       124
#define SUBFE_XO     136
#define ADDE_XO      138
#define MTCRF_XO     144
#define MTMSR_XO     146
#define STWCX__XO    150
#define STWX_XO      151
#define WRTEEI_XO    163
#define SUBFZE_XO    200
#define ADDZE_XO     202
#define STBX_XO      215
#define ADDME_XO     234
#define MULLW_XO     235
#define ADD_XO       266
#define LHZX_XO      279
#define XOR_XO       316
#define MFSPR_XO     339
#define LHAX_XO      343
#define STHX_XO      407
#define ORC_XO       412
#define OR_XO        444
#define DIVWU_XO     459
#define MTSPR_XO     467
#define NAND_XO      476
#define DIVW_XO      491
#define LWBRX_XO     534
#define SRW_XO       536
#define SYNC_XO      598
#define STWBRX_XO    662
#define LHBRX_XO     790
#define SRAW_XO      792
#define SRAWI_XO     824
#define STHBRX_XO    918
#define EXTSH_XO     922
#define EXTSB_XO     954
#define LWZ_XO       0
#define LBZ_XO       0
#define STW_XO       0
#define STB_XO       0
#define LHZ_XO       0
#define LHA_XO       0
#define STH_XO       0
#define LMW_XO       0
#define STMW_XO      0
#define LBZU_XO	 	 0
#define LBZUX_XO	 119
#define LHZU_XO	 	 0
#define LHZUX_XO	 311
#define LHAU_XO	 	 0
#define LHAUX_XO	 375
#define LWZU_XO	 	 0
#define LWZUX_XO	 55
#define STBU_XO	 	 0
#define STBUX_XO	 247
#define STHU_XO	 	 0
#define STHUX_XO	 439
#define STWU_XO	 	 0
#define STWUX_XO	 183


#endif
