// define D-Form
`define D_RT_WIDTH 5
`define D_RT [6:10]
`define D_D_WIDTH 16
`define D_D [16:31]
`define D_RS_WIDTH 5
`define D_RS [6:10]
`define D_RD_WIDTH 5
`define D_RD [6:10]
`define D_SI_WIDTH 16
`define D_SI [16:31]
`define D_RA_WIDTH 5
`define D_RA [11:15]
`define D_OPCD_WIDTH 6
`define D_OPCD [0:5]

// define DS-Form
`define DS_RT_WIDTH 5
`define DS_RT [6:10]
`define DS_XO_WIDTH 2
`define DS_XO [30:31]
`define DS_RS_WIDTH 5
`define DS_RS [6:10]
`define DS_RD_WIDTH 5
`define DS_RD [6:10]
`define DS_RA_WIDTH 5
`define DS_RA [11:15]
`define DS_OPCD_WIDTH 6
`define DS_OPCD [0:5]
`define DS_DS_WIDTH 14
`define DS_DS [16:29]

// define X-Form
`define X_RT_WIDTH 5
`define X_RT [6:10]
`define X_RS_WIDTH 5
`define X_RS [6:10]
`define X_OPCD_WIDTH 6
`define X_OPCD [0:5]
`define X_RA_WIDTH 5
`define X_RA [11:15]
`define X_RB_WIDTH 5
`define X_RB [16:20]
`define X_XO_WIDTH 10
`define X_XO [21:30]

// define XO-Form
`define XO_RT_WIDTH 5
`define XO_RT [6:10]
`define XO_XO_WIDTH 9
`define XO_XO [22:30]
`define XO_OE_WIDTH 1
`define XO_OE [21:21]
`define XO_RA_WIDTH 5
`define XO_RA [11:15]
`define XO_RB_WIDTH 5
`define XO_RB [16:20]
`define XO_Rc_WIDTH 1
`define XO_Rc [31:31]
`define XO_OPCD_WIDTH 6
`define XO_OPCD [0:5]

